# Default values for healthcoreapi chart.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: your-container-registry/healthcoreapi
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: healthcoreapi.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resource allocation for production workloads
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Health check configuration
healthCheck:
  livenessProbe:
    enabled: true
    path: /health/live/
    initialDelaySeconds: 30
    timeoutSeconds: 5
  readinessProbe:
    enabled: true
    path: /health/ready/
    initialDelaySeconds: 10
    timeoutSeconds: 3

# Environment-specific configuration
environment: development

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
