# Generated by Django 5.2 on 2025-12-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="mrn",
            field=models.CharField(
                blank=True,
                help_text="Medical Record Number",
                max_length=255,
                unique=True,
            ),
        ),
    ]
