"""
Django settings for the project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Enable runtime support for generic type parameters in Django
import django_stubs_ext

django_stubs_ext.monkeypatch()

import os  # noqa: E402
from datetime import timedelta  # noqa: E402
from pathlib import Path  # noqa: E402
from typing import Any  # noqa: E402

import dj_database_url  # noqa: E402
from decouple import Csv, config  # noqa: E402

# Imports for optional features

import sentry_sdk  # noqa: E402, F401
from sentry_sdk.integrations.django import DjangoIntegration  # noqa: E402, F401
from sentry_sdk.integrations.redis import RedisIntegration  # noqa: E402, F401
from sentry_sdk.integrations.celery import CeleryIntegration  # noqa: E402, F401


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
APPS_DIR = BASE_DIR / "apps"

# GENERAL
# ------------------------------------------------------------------------------
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv(), default="*")
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:5173")
# Add 'web' for internal Docker network (Prometheus scraping)
if "web" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = list(ALLOWED_HOSTS) + ["web"]

# Version for health checks and API docs
VERSION = "0.1.0"

# Application definition
# ------------------------------------------------------------------------------
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "storages",
    "social_django",  # Google OAuth integration
    # Auth & Registration
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
]

SITE_ID = 1

if "yes" == "yes":
    THIRD_PARTY_APPS.append("django_celery_beat")

LOCAL_APPS = [
    "src.apps.core",
    "src.apps.patients",
    "src.apps.practitioners",
    "src.apps.scheduling",
    "src.apps.admissions",
    "src.apps.results",
    "src.apps.shifts",
    "src.apps.experience",
    "src.apps.departments",
    "src.apps.pharmacy",
    "src.apps.equipment",
    "src.apps.orders",
    # Your local apps go here
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS
INSTALLED_APPS += ["django_prometheus"]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "src.apps.core.middleware.RequestLoggingMiddleware",
    "src.apps.core.middleware.TimeoutMiddleware",
    "src.apps.core.middleware.IdempotencyMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # allauth
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "healthcoreapi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR / "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "healthcoreapi.wsgi.application"
ASGI_APPLICATION = "healthcoreapi.asgi.application"

# Database
# ------------------------------------------------------------------------------
DATABASES = {"default": dj_database_url.config(default=config("DATABASE_URL"))}
DATABASES["default"]["ATOMIC_REQUESTS"] = True

# Database connection pooling for performance
CONN_MAX_AGE = config("CONN_MAX_AGE", default=60, cast=int)
DATABASES["default"]["CONN_MAX_AGE"] = CONN_MAX_AGE

# Cache configuration using django-redis
# ------------------------------------------------------------------------------
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config("CACHE_URL", default="redis://redis:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "retry_on_timeout": True,
            },
            "IGNORE_EXCEPTIONS": True,  # Don't crash if Redis is down
        },
        "KEY_PREFIX": "healthcoreapi",
        "TIMEOUT": 300,  # 5 minutes default timeout
    }
}

# Session storage
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 3600  # 1 hour

# Password validation
# ------------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# ------------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# ------------------------------------------------------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": os.path.join(BASE_DIR, "media"),
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# ------------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework
# ------------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
    },
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ]
    + (["rest_framework.renderers.BrowsableAPIRenderer"] if DEBUG else []),
}

# DRF Spectacular
# ------------------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "HealthCoreAPI API",
    "DESCRIPTION": "**HealthCore API** is a secure, scalable, and high-performance backend system for complete hospital operations management. This project serves as the technological backbone for managing patients, appointments, electronic health records, and administrative processes, built upon an enterprise-grade foundation.",
    "VERSION": VERSION,
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/v1",
    "COMPONENT_SPLIT_REQUEST": True,
    "SORT_OPERATIONS": False,
    # Optimized schema coercion for primary keys
    "SCHEMA_COERCION_PATH_PK_SUFFIX": True,
    "DISABLE_ERRORS_AND_WARNINGS": not DEBUG,
}

# CORS
# ------------------------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=True, cast=bool)
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=Csv(), default="")

if not DEBUG:
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOWED_HEADERS = [
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-correlation-id",
        "x-csrftoken",
        "x-requested-with",
    ]


# Celery
# ------------------------------------------------------------------------------
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default="redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BEAT_SCHEDULE: dict[str, Any] = {
    # Daily appointment reminders at 8 AM UTC
    "send-appointment-reminders": {
        "task": "src.apps.scheduling.tasks.send_appointment_reminders",
        "schedule": timedelta(hours=24),  # Daily
        "options": {"expires": 3600},  # Task expires after 1 hour if not executed
    },
    # Hourly auto-completion of past appointments
    "auto-complete-past-appointments": {
        "task": "src.apps.scheduling.tasks.auto_complete_past_appointments",
        "schedule": timedelta(hours=1),  # Hourly
        "options": {"expires": 1800},  # Task expires after 30 minutes
    },
    # Weekly slot generation on Mondays at 00:00 UTC
    "generate-future-slots": {
        "task": "src.apps.scheduling.tasks.generate_future_slots",
        "schedule": timedelta(days=7),  # Weekly
        "options": {"expires": 7200},  # Task expires after 2 hours
    },
}

# KAFKA CONFIGURATION
# ------------------------------------------------------------------------------
KAFKA_BOOTSTRAP_SERVERS = config("KAFKA_BOOTSTRAP_SERVERS", default="kafka:9092")
KAFKA_ENABLED = config("KAFKA_ENABLED", default=True, cast=bool)
KAFKA_TOPIC_PREFIX = config("KAFKA_TOPIC_PREFIX", default="healthcore")

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_TASK_ALWAYS_EAGER = config("CELERY_TASK_ALWAYS_EAGER", default=DEBUG, cast=bool)
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True

# Celery task routing and optimization
CELERY_TASK_ROUTES = {
    "*.tasks.send_email": {"queue": "email"},
    "*.tasks.process_data": {"queue": "processing"},
}


# Security Settings
# ------------------------------------------------------------------------------
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

if not DEBUG:
    SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
    SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# ------------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.json.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(module)s %(funcName)s %(lineno)d %(process)d %(thread)d %(message)s",
        },
        "verbose": {
            "format": "{levelname} {asctime} {name} {module} {funcName} {lineno} {process:d} {thread:d} [correlation_id={correlation_id}] {message}",
            "style": "{",
        },
    },
    "filters": {
        "correlation_id": {
            "()": "src.apps.core.logging.CorrelationIDFilter",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "json" if not DEBUG else "verbose",
            "filters": ["correlation_id"],
        },
    },
    "root": {
        "level": "INFO",
        "handlers": ["console"],
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.db.backends": {
            "level": "ERROR",
            "handlers": ["console"],
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "src": {  # Your local apps
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

HEALTH_CHECK_ENABLED = config("HEALTH_CHECK_ENABLED", default=True, cast=bool)

ADMIN_URL = config("ADMIN_URL", default="admin/")


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

# dj-rest-auth settings
REST_USE_JWT = True
JWT_AUTH_COOKIE = "healthcore-auth"
JWT_AUTH_REFRESH_COOKIE = "healthcore-refresh"

# Google OAuth Configuration
# ------------------------------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    "social_core.backends.google.GoogleOAuth2",  # Google OAuth2
    "django.contrib.auth.backends.ModelBackend",  # Default Django auth
    "allauth.account.auth_backends.AuthenticationBackend",  # allauth
]

# dj-rest-auth & allauth registration settings
ACCOUNT = {
    "SIGNUP_FIELDS": {
        "username": {"required": True},
        "email": {"required": True},
    },
    "LOGIN_BY_CODE_ENABLED": False,
    "EMAIL_VERIFICATION": "optional",
    "AUTHENTICATION_METHOD": "username_email",
}
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"

# Suppress dj-rest-auth internal deprecation warnings
# The library hasn't been updated yet to use SIGNUP_FIELDS API
import warnings  # noqa: E402

warnings.filterwarnings(
    "ignore",
    message="app_settings.USERNAME_REQUIRED is deprecated",
    category=UserWarning,
    module="dj_rest_auth.registration.serializers",
)
warnings.filterwarnings(
    "ignore",
    message="app_settings.EMAIL_REQUIRED is deprecated",
    category=UserWarning,
    module="dj_rest_auth.registration.serializers",
)

# Development: Print emails to console instead of sending (fixes 500 error)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Google OAuth credentials (from Google Cloud Console)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config("GOOGLE_OAUTH_CLIENT_ID", default="")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config("GOOGLE_OAUTH_CLIENT_SECRET", default="")

# OAuth redirect URLs
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = config(
    "GOOGLE_OAUTH_REDIRECT_URI",
    default="http://localhost:8000/api/auth/complete/google-oauth2/",
)

# Scopes to request from Google
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]

# Custom pipeline to assign default PATIENT role (ADR 0002 requirement)
SOCIAL_AUTH_PIPELINE = (
    # Get the information we can about the user and return it in a simple
    # format to create the user instance later. In some cases the details are
    # already part of the auth response from the provider, but sometimes this
    # could hit a provider API.
    "social_core.pipeline.social_auth.social_details",
    # Get the social uid from whichever service we're authing thru. The uid is
    # the unique identifier of the given user in the provider.
    "social_core.pipeline.social_auth.social_uid",
    # Verifies that the current auth process is valid within the current
    # project, this is where emails and domains whitelists are applied (if
    # defined).
    "social_core.pipeline.social_auth.auth_allowed",
    # Checks if the current social-account is already associated in the site.
    "social_core.pipeline.social_auth.social_user",
    # Make up a username for this person, appends a random string at the end if
    # there's any collision.
    "social_core.pipeline.user.get_username",
    # Create a user account if we haven't found one yet.
    "social_core.pipeline.user.create_user",
    # ✅ CUSTOM: Assign default PATIENT role to new users (ADR 0002)
    "src.apps.core.pipeline.assign_default_patient_role",
    # Create the record that associates the social account with the user.
    "social_core.pipeline.social_auth.associate_user",
    # Populate the extra_data field in the social record with the values
    # specified by settings (and the default ones like access_token, etc).
    "social_core.pipeline.social_auth.load_extra_data",
    # Update the user record with any changed info from the auth service.
    "social_core.pipeline.user.user_details",
)

# OAuth redirect URLs - redirect to backend callback that generates JWT tokens
SOCIAL_AUTH_LOGIN_REDIRECT_URL = "/api/auth/oauth/callback/"
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = "/api/auth/oauth/callback/"

# Security settings for OAuth
SOCIAL_AUTH_GOOGLE_OAUTH2_USE_DEPRECATED_API = False
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {"access_type": "offline"}


# Sentry
# ------------------------------------------------------------------------------
SENTRY_DSN = config("SENTRY_DSN", default=None)
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
            RedisIntegration(),
        ],
        traces_sample_rate=config("SENTRY_TRACES_SAMPLE_RATE", default=0.1, cast=float),
        send_default_pii=True,
        environment=config("SENTRY_ENVIRONMENT", default="development"),
        release=VERSION,
    )

# AI Integration Configuration
# ------------------------------------------------------------------------------
# Gemini (Default - Free Tier Available)
GEMINI_API_KEY = config("GEMINI_API_KEY", default=None)
GEMINI_MODEL = config("GEMINI_MODEL", default="models/gemini-2.5-flash")

# OpenAI (Alternative - Requires Paid Credits)
OPENAI_API_KEY = config("OPENAI_API_KEY", default=None)
OPENAI_MODEL = config("OPENAI_MODEL", default="gpt-3.5-turbo")

# Azure OpenAI (Enterprise/Cloud)
AZURE_OPENAI_API_KEY = config("AZURE_OPENAI_API_KEY", default=None)
AZURE_OPENAI_ENDPOINT = config("AZURE_OPENAI_ENDPOINT", default="")
AZURE_OPENAI_DEPLOYMENT_NAME = config(
    "AZURE_OPENAI_DEPLOYMENT_NAME", default="gpt-4o-mini"
)
AZURE_OPENAI_API_VERSION = config(
    "AZURE_OPENAI_API_VERSION", default="2024-02-15-preview"
)
