services:
  web:
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=healthcoreapi.settings.development
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "8000:8000"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    profiles:
      - tools

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - tools
