services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: gunicorn healthcoreapi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - staticfiles:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/usr/src/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: celery -A healthcoreapi.celery worker -l info
    env_file:
      - .env
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: celery -A healthcoreapi.celery beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - redis


volumes:
  redis_data:
  staticfiles:
