# Generated by Django 5.2 on 2025-12-17 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_idempotencykey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfessionalRoleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "role_requested",
                    models.CharField(
                        choices=[
                            ("Doctors", "Doctor"),
                            ("Nurses", "Nurse"),
                            ("Pharmacists", "Pharmacist"),
                            ("Receptionists", "Receptionist"),
                        ],
                        help_text="Professional role being requested",
                        max_length=50,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Professional license number", max_length=100
                    ),
                ),
                (
                    "license_state",
                    models.CharField(
                        help_text="State/country where license was issued",
                        max_length=50,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="Medical specialty (for doctors)",
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Reason for requesting this role"),
                ),
                (
                    "license_document",
                    models.FileField(
                        help_text="Scanned copy of professional license",
                        upload_to="credentials/licenses/",
                    ),
                ),
                (
                    "certification_document",
                    models.FileField(
                        blank=True,
                        help_text="Board certification or additional credentials (optional)",
                        upload_to="credentials/certs/",
                    ),
                ),
                (
                    "employment_verification",
                    models.FileField(
                        blank=True,
                        help_text="Employment verification letter (optional)",
                        upload_to="credentials/employment/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Current status of the request",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when request was reviewed",
                        null=True,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about the review decision"
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_role_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting professional role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Professional Role Request",
                "verbose_name_plural": "Professional Role Requests",
                "ordering": ["-created_at"],
                "permissions": [
                    ("review_role_requests", "Can review professional role requests")
                ],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_profes_status_cb4ad0_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="core_profes_user_id_7748e4_idx"
                    ),
                ],
            },
        ),
    ]
