apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: https://ca-prometheus.icyocean-8228f51c.centralus.azurecontainerapps.io
    isDefault: true
    editable: true
