"""
Data Transfer Objects for Kafka event payloads.

Defines structured types for audit events to ensure type safety
and consistency across the application.
"""

from dataclasses import asdict, dataclass
from datetime import datetime
from typing import Any, Optional


@dataclass
class AuditEventPayload:
    """
    Nested payload structure for audit events.

    Matches the Go consumer's EventPayload.Payload struct.
    """

    actor_id: str
    action: str
    target_id: str
    resource_type: str
    ip_address: str
    user_agent: str
    details: str  # JSON string


@dataclass
class KafkaAuditEvent:
    """
    Top-level Kafka event structure for audit logs.

    Matches the Go consumer's EventPayload struct:
    ```go
    type EventPayload struct {
        EventID   string `json:"event_id"`
        Type      string `json:"type"`
        Timestamp string `json:"timestamp"`
        Payload   struct {...} `json:"payload"`
    }
    ```
    """

    event_id: str
    type: str
    timestamp: str
    payload: AuditEventPayload

    @classmethod
    def create(
        cls,
        actor_id: str,
        action: str,
        target_id: Optional[str] = None,
        resource_type: str = "",
        ip_address: str = "",
        user_agent: str = "",
        details_dict: Optional[dict[str, Any]] = None,
    ) -> "KafkaAuditEvent":
        """
        Factory method to create a KafkaAuditEvent with proper defaults.

        Args:
            actor_id: ID of the user performing the action
            action: Action performed (e.g., 'PATIENT_VIEW')
            target_id: ID of the target resource (defaults to actor_id)
            resource_type: Type of resource (e.g., 'PATIENT')
            ip_address: Source IP address
            user_agent: Client user agent
            details_dict: Additional context as a dictionary

        Returns:
            KafkaAuditEvent instance ready to be serialized
        """
        import json

        return cls(
            event_id="",  # Generated by Go service
            type="audit.log",
            timestamp=datetime.utcnow().isoformat() + "Z",
            payload=AuditEventPayload(
                actor_id=actor_id,
                action=action,
                target_id=target_id or actor_id,
                resource_type=resource_type,
                ip_address=ip_address,
                user_agent=user_agent,
                details=json.dumps(details_dict or {}),
            ),
        )

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return asdict(self)
