# Generated by Django 5.2 on 2025-12-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this equipment record is active"
            ),
        ),
    ]
