apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-healthcoreapi
  labels:
    app: healthcoreapi
    environment: {{ .Values.environment | default "development" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: healthcoreapi
  template:
    metadata:
      labels:
        app: healthcoreapi
        environment: {{ .Values.environment | default "development" }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live/
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready/
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment | default "development" }}
