# Generated by Django 5.2 on 2025-10-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active"
                    ),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("given_name", models.CharField(max_length=255)),
                ("family_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        help_text="e.g., Physician, Nurse, Technician", max_length=100
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Cardiology, Radiology",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner",
                "verbose_name_plural": "Practitioners",
                "ordering": ["family_name", "given_name"],
            },
        ),
    ]
