# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audit.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'audit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udit.proto\x12\x05\x61udit\"\xa9\x01\n\x0fLogEventRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x11\n\ttarget_id\x18\x03 \x01(\t\x12\x15\n\rresource_type\x18\x04 \x01(\t\x12\x12\n\nip_address\x18\x05 \x01(\t\x12\x12\n\nuser_agent\x18\x06 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\"5\n\x10LogEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t\"K\n\x13GetAuditLogsRequest\x12\x11\n\ttarget_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x12\n\nnext_token\x18\x03 \x01(\t\"\xa5\x01\n\rAuditLogEntry\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x11\n\ttarget_id\x18\x04 \x01(\t\x12\x15\n\rresource_type\x18\x05 \x01(\t\x12\x12\n\nip_address\x18\x06 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\"N\n\x14GetAuditLogsResponse\x12\"\n\x04logs\x18\x01 \x03(\x0b\x32\x14.audit.AuditLogEntry\x12\x12\n\nnext_token\x18\x02 \x01(\t2\x94\x01\n\x0c\x41uditService\x12;\n\x08LogEvent\x12\x16.audit.LogEventRequest\x1a\x17.audit.LogEventResponse\x12G\n\x0cGetAuditLogs\x12\x1a.audit.GetAuditLogsRequest\x1a\x1b.audit.GetAuditLogsResponseBEZCgithub.com/Daniel-Q-Reis/HealthCoreAPI/services/audit-service/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/Daniel-Q-Reis/HealthCoreAPI/services/audit-service/proto'
  _globals['_LOGEVENTREQUEST']._serialized_start=23
  _globals['_LOGEVENTREQUEST']._serialized_end=192
  _globals['_LOGEVENTRESPONSE']._serialized_start=194
  _globals['_LOGEVENTRESPONSE']._serialized_end=247
  _globals['_GETAUDITLOGSREQUEST']._serialized_start=249
  _globals['_GETAUDITLOGSREQUEST']._serialized_end=324
  _globals['_AUDITLOGENTRY']._serialized_start=327
  _globals['_AUDITLOGENTRY']._serialized_end=492
  _globals['_GETAUDITLOGSRESPONSE']._serialized_start=494
  _globals['_GETAUDITLOGSRESPONSE']._serialized_end=572
  _globals['_AUDITSERVICE']._serialized_start=575
  _globals['_AUDITSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
