# Generated by Django 5.2 on 2025-12-09 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        ("patients", "0001_initial"),
        ("practitioners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LAB", "Laboratory"),
                            ("IMAGING", "Imaging"),
                            ("PROCEDURE", "Procedure"),
                            ("REFERRAL", "Referral"),
                        ],
                        default="LAB",
                        help_text="Category of service requested",
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Service code (e.g., LOINC, CPT, or internal code)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Human-readable description of the service",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On Hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ENTERED_IN_ERROR", "Entered in Error"),
                        ],
                        default="ACTIVE",
                        help_text="Current status of the order",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("ASAP", "ASAP"),
                            ("STAT", "STAT (Immediate)"),
                        ],
                        default="ROUTINE",
                        help_text="Urgency of the request",
                        max_length=20,
                    ),
                ),
                (
                    "requested_date",
                    models.DateTimeField(
                        help_text="When the service should be performed"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Clinical reason/indication for the order"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional instructions for the performer",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient who is the subject of the order",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="patients.patient",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="Practitioner who requested the service",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_requested",
                        to="practitioners.practitioner",
                    ),
                ),
                (
                    "target_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department responsible for fulfilling the order",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_orders",
                        to="departments.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Order",
                "verbose_name_plural": "Clinical Orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="orders_clin_status_8badb9_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="orders_clin_priorit_eccbe0_idx"
                    ),
                    models.Index(
                        fields=["patient"], name="orders_clin_patient_cd11f7_idx"
                    ),
                    models.Index(
                        fields=["requester"], name="orders_clin_request_a8fffa_idx"
                    ),
                ],
            },
        ),
    ]
